### PR TITLE
lvgl: upgrade to release/v9.2

### PR DESCRIPTION
**Pull request by XuNeo**
## Summary

Upgrade LVGL to release ~v9.2~. v9.2.1

Relates Issue: https://github.com/apache/nuttx-apps/issues/2461.

## Impact

LVGL may have incompatible API changes in v9.2. You may need to manually fix them. 
Please report to LVGL if any problems.

## Testing
I compiled and tested with `sim:lvgl_fb` and `stm32f429i-disco:lvgl`. Both can compile without warning and launches successfully.

The `lvgl/Kconfig` is still copied from lvgl/lvgl/Kconfig. ~The file version mismatch check will be added in next release(v9.2.1)~ Added in this PR.

### CODE REVIEW

**Comment by cederom** [comment]
Thank you @XuNeo :-) Shall we wait for LVGL release 9.2.1? https://github.com/lvgl/lvgl/pull/6789 is already merged into LVGL upstream :-)

Do you know when LVGL 9.2.1 will be released @kisvegabor ? :-)

**Comment by XuNeo** [comment]
> Shall we wait for LVGL release 9.2.1?

Yes. Let's wait for https://github.com/lvgl/lvgl/pull/6817 to fix current warnings reported in NuttX.

**Comment by kisvegabor** [comment]
> Do you know when LVGL 9.2.1 will be released @kisvegabor ? :-)

Targeting beginning of October.

**Comment by cederom** [comment]
Thank you @kisvegabor fingers crossed, please let us know how we can help on the NuttX RTOS side :-)

**Comment by XuNeo** [comment]
Upgraded to v9.2.1.

Tested with https://github.com/lvgl/lvgl/pull/6981 and no more warnings. :)

**Comment by cederom** [comment]
This should fix https://github.com/apache/nuttx-apps/issues/2461, https://github.com/apache/nuttx/issues/13839, https://github.com/apache/nuttx/issues/13825 on LVGL 9.2.1 release :-)

**Comment by jerpelea** [comment]
https://github.com/lvgl/lvgl/pull/6981 is merged

**Comment by xiaoxiang781216** [comment]
@XuNeo v9.2.1 just release, let' rebase your patch to finish the upgrade.

**Comment by XuNeo** [comment]
Let's wait for Gabor to create a release based on the release/v9.2 branch.

**Comment by kisvegabor** [comment]
I'm just waiting for the final reports about it's really working on all frameworks.  Let's target October 14 with the release.

**Comment by jerpelea** [comment]
@XuNeo please rebase

**Comment by kisvegabor** [comment]
We got reports about some performance regression so will need a few more days. :slightly_frowning_face:

**Comment by cederom** [comment]
Okay @XuNeo the `release/v9.2` branch is here and this will contain 9.2.1 release code that is 99% ready we can proceed with the PR :-)

https://github.com/lvgl/lvgl/tree/release/v9.2

**Comment by cederom** [comment]
As LVGL tag v9.2.1 is not here yet we may use https://github.com/lvgl/lvgl/archive/refs/heads/release/v9.2.zip for testing :-)

**Comment by XuNeo** [comment]
PR updated to target LVGL latest release/v9.2 branch.
Locally tested `sim:lvgl_fb` and all good.

**Comment by cederom** [comment]
Thank you @XuNeo !! Looks like we are ready for LVGL 9.2.1 :-)

@fjpanag @TimJTi @raiden00pl could you please verify this PR on your hardware? This PR upgrades LVGL to 9.2.1 that we plan to put on NuttX 12.7.0 :-) It still uses release/v9.2 branch package archive but it contains 99% of 9.2.1 code (9.2.1 release will be kept in this branch too), we will update the URL when 9.2.1 is released :-)

**Review by lupyuen — APPROVED** [review]

**Comment by cederom** [comment]
**!!!DO NOT YET MERGE THIS PR UNTIL LVGL 9.2.1 IS RELEASED!!!**

Shall we still keep it in a "draft" state until 9.2.1 is officially out? :-)

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by raiden00pl** [comment]
it looks like for `lvgldemo` example,  `\r` is missing in console output:

image

**Comment by cederom** [comment]
> @raiden00pl: it looks like for `lvgldemo` example (stm32f746g-disco), `\r` is missing in console output:

Thanks @raiden00pl :-) Isn't this terminal setting? Other apps output works fine?

**Review by jerpelea — APPROVED** [review]

**Comment by raiden00pl** [comment]
> > @raiden00pl: it looks like for `lvgldemo` example (stm32f746g-disco), `\r` is missing in console output:
> 
> Thanks @raiden00pl :-) Isn't this terminal setting? Other apps output works fine?

fixed with https://github.com/apache/nuttx/pull/14362

**Comment by jerpelea** [comment]
backport https://github.com/apache/nuttx-apps/pull/2764

**Comment by cederom** [comment]
LVGL 9.2.1 release is planned for tomorrow :-)

**Comment by cederom** [comment]
As promissed LVGL 9.2.1 is out! :-)
https://github.com/lvgl/lvgl/archive/refs/tags/v9.2.1.zip
https://github.com/lvgl/lvgl/archive/refs/tags/v9.2.1.tar.gz

**Comment by XuNeo** [comment]
Verified with sim:lvgl_fb. All good :)

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]

**Pull request merged**
