### PR TITLE
Adjust the apps/benchmarks directory and add some new Profile tools

### PR DESCRIPTION
**Pull request by crafcat7**
## Summary
1. I moved some Perfile tools from apps/testing -> apps/benchmarks to match their behavior.
It mainly involves the existing tools of NuttX:
- ramspeed
- cachespeed
- osperf
- iozone
- superPI

2. Added some new external Profile tools and adapted them to NuttX:
- Dhrystone
- fio
- coremark-pro

## Impact
1. For existing testing tools, such as Ramspeed, Cachespeed, etc., the enabling macro prefix has been changed from TESTING_XXXX to BENCHMARK_XXXX
2. Add some new external performance testing tools
## Testing
For the new Profile Tools, I made the adaptation changes into a patch to ensure that it can be enabled in NuttX

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by raiden00pl** [comment]
@crafcat7 please update the Documentation to reflect your changes (move directories from https://github.com/apache/nuttx/tree/master/Documentation/applications/testing to https://github.com/apache/nuttx/tree/master/Documentation/applications/benchmarks)

**Comment by crafcat7** [comment]
> @crafcat7 please update the Documentation to reflect your changes (move directories from https://github.com/apache/nuttx/tree/master/Documentation/applications/testing to https://github.com/apache/nuttx/tree/master/Documentation/applications/benchmarks)

Done, I have submitted the document update to PR: https://github.com/apache/nuttx/pull/12087

**Review by cederom — APPROVED** [review]
thanks :-) i have restarted ci checks :-)

**Comment by xiaoxiang781216** [comment]
@crafcat7 please fix the ci error.

**Comment by crafcat7** [comment]
> @crafcat7 please fix the ci error.



> @crafcat7 please fix the ci error.

Done,Modified the naming of macros affected by the modification in some configurations
https://github.com/apache/nuttx/pull/12094

**Comment by cederom** [comment]
ci restarted :-)

**Pull request merged**
