### PR TITLE
lte/lapi: Remove the PIN feature

### PR DESCRIPTION
**Pull request by SPRESENSE**
## Summary
Remove the PIN feature, because the SIM may accidentally become unusable.

## Impact
Only LTE feature.

## Testing
Test with Spresense LTE board.

### CODE REVIEW

**Comment by cederom** [comment]
* It this code to be removed works well in general?
* What will happen with SIM that requires PIN and the code gets now removed?
* Why not add option to disable that functionality and not delete working code?

**Comment by raiden00pl** [comment]
Isn't it the user's responsibility to use the API correctly? If the API is dangerous for some reason, it is better to hide it behind an Kconfig option than to remove it completely.

**Comment by hartmannathan** [comment]
I noticed the APIs do not have docstrings. Perhaps as @cederom and @raiden00pl suggest, don't delete the APIs? Instead, consider adding a comment block before the functions, consistent with most of NuttX, with text like, "WARNING: This API is dangerous because [reason]." If the caller needs to do something specific to mitigate the problems, maybe document that here also.

**Comment by acassis** [comment]
ping @SPRESENSE

**Comment by acassis** [comment]
Closing this PR, let's keep the PIN support

**Pull request closed without merging**
