### PR TITLE
netutils/webclient: Fix bug that the socket is not close

### PR DESCRIPTION
**Pull request by SPRESENSE**
## Summary
Fix to close socket when it fails to resolve hostname.

## Impact
webclient. 

## Testing
Test with Spresense LTE board.

### CODE REVIEW

**Review by jerpelea — APPROVED** [review]

**Review by jerpelea — CHANGES_REQUESTED** [review]
please fix the commit

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
Please fix the style issue, @SPRESENSE

**Comment by SPRESENSE** [comment]
@jerpelea @xiaoxiang781216 
I have fixed the style issue. Please check.

**Comment by xiaoxiang781216** [comment]
@acassis and @LuchianMihai does https://github.com/apache/nuttx/pull/12794 change good?

**Comment by LuchianMihai** [comment]
Strictly regarding the [C Coding Standard](https://nuttx.apache.org/docs/latest/contributing/coding_style.html), is stated that the:

> Comments to the right of statements in C source files are discouraged.

> Indentation Comments should, typically, be placed before the code section to which they apply. The comment indentation should be the same as the follow indentation rules as the following code (if applicable).

Now there is nothing explicitly stating that there should not be comments to the right of __if statements__, but I saw no comment at the right of the statement throughout the examples given there (in C Coding Standard page).

My change will report an error if there is anything to the right of the statement, because checking that the comment is correctly formatted (as the comment should be indented accordingly) would be harder, and maybe not worth the time penalty for checking that corner case. Maybe we can report this as an warning?

**Comment by xiaoxiang781216** [comment]
> Hi @xiaoxiang781216 , @acassis
> 
> Strictly regarding the [C Coding Standard](https://nuttx.apache.org/docs/latest/contributing/coding_style.html), is stated that the:
> 
> > Comments to the right of statements in C source files are discouraged.
> 
> > Indentation Comments should, typically, be placed before the code section to which they apply. The comment indentation should be the same as the follow indentation rules as the following code (if applicable).
> 
> Now there is nothing explicitly stating that there should not be comments to the right of **if statements**, but I saw no comment at the right of the statement throughout the examples given there (in C Coding Standard page).
> 

@patacongo @acassis what's your opinion?

> My change will report an error if there is anything to the right of the statement, because checking that the comment is correctly formatted (as the comment should be indented accordingly) would be harder, and maybe not worth the time penalty for checking that corner case. Maybe we can report this as an warning?

The code base is large, new check will break many codes which pass the ci before. So, we need be more conservative here.

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by LuchianMihai** [comment]
Just run a quick search through the codebase:
> grep -r "if (.*)\ */\*" | wc -l         # This reports the total number of occurrences: 78

> grep -r "if (.*)\ */\*" -l | wc -l      # This reports the total number of independent files affected: 32

I'm only counting correctly formatted if statements which are followed by spaces until the beginning of a comment is found. We add a few more changes if I include incorrectly formatted if statements.

But nevertheless, it's quite a big surface area as it is, maybe my changes are not adding more value than adding issues.

**Pull request merged**
