### PR TITLE
examples/amg88xx: add example for amg88xx driver

### PR DESCRIPTION
**Pull request by LuchianMihai**
## Summary
Simple example for the amg88xx driver

### CODE REVIEW

**Comment by LuchianMihai** [comment]
> @LuchianMihai did you have time to convert the driver to video/camera interface? Case you don't, maybe we should merge it as normal driver, because is better to have a driver anyway because it could become the base for other people to modify it

Hi @acassis, 
I had to deliver the project I was working on so right now I do not have any sensor board to work on, I've designed an shield similar to [this](https://www.mikroe.com/grid-eye-click?srsltid=AfmBOoqL-SjB5Lr2xmIqdPZc26EOHcOW3saPend1m2Lm_VMXaxQAfQk3) one. Right now is in transit. 
Also I still have a single sensor (hopefully working) that I will solder on the board.
So for the moment the development is blocked. Maybe an better idea would be to close as is, and continue when I have needed hardware.

**Comment by LuchianMihai** [comment]
> @LuchianMihai instead of closing it you can just convert to draft, it way it is easier to track later

Close, as in merge my PR

**Comment by LuchianMihai** [comment]
Hi @acassis,
Can you point out what went wrong here?

**Comment by xiaoxiang781216** [comment]
> Hi @acassis, Can you point out what went wrong here?

look like it's the temp network error:
```
====================================================================================
Configuration/Tool: bl602evb/wifi
2024-08-29 15:16:22
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0

100 12993    0 12993    0     0   2524      0 --:--:--  0:00:05 --:--:--  2524
100  496k    0  496k    0     0  93110      0 --:--:--  0:00:05 --:--:-- 1560k
curl: (16) Error in the HTTP2 framing layer
make[1]: *** [v1.9.1-ble-test.zip] Error 16
make[1]: Target `context' not remade because of errors.
make: *** [arch/risc-v/src/.context] Error 2
make: Target `all' not remade because of errors.
/Users/runner/work/nuttx-apps/nuttx-apps/sources/nuttx/tools/testbuild.sh: line 378: /Users/runner/work/nuttx-apps/nuttx-apps/sources/nuttx/../nuttx/nuttx.manifest: No such file or directory
  Normalize bl602evb/wifi
```

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — APPROVED** [review]
please add a commit message

**Pull request merged**
