### PR TITLE
testing: Swith up_perf_xxx to perf_xxx

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

follow up the the kernel change:
https://github.com/apache/nuttx/pull/10834

## Impact

no

## Testing

ci

### CODE REVIEW

**Comment by TaiJuWu** [comment]
I found a bug about workqueue and already send a PR to your branch of this PR.
Please review.

**Comment by xiaoxiang781216** [comment]
> I found a bug about workqueue and already send a PR to your branch of this PR. Please review. Thanks a lot.

where is it?

**Comment by TaiJuWu** [comment]
> > I found a bug about workqueue and already send a PR to your branch of this PR. Please review. Thanks a lot.
> 
> where is it?

https://github.com/xiaoxiang781216/incubator-nuttx-apps/pull/6

**Comment by xiaoxiang781216** [comment]
ok, I incorporate your change into this pr. @pkarashchenko please review the change again.

**Review by acassis — APPROVED** [review]

**Review by anchao — APPROVED** [review]

**Pull request merged**
