### PR TITLE
module build:replace BUILD_LOADABLE with MODULES

### PR DESCRIPTION
**Pull request by xuxin930**
## Summary

this patch is relate to: https://github.com/apache/nuttx/pull/13452

### CODE REVIEW

**Review by cederom — COMMENTED** [review]
@patacongo please advise on nomenclature change :-)

**Comment by patacongo** [comment]
> @patacongo please advise on nomenclature change :-)

I am not so much involved these days but in the past, configuration names began with CONFIG_ (of course) then what was being modified ( for example, NET_ for anyting affecting the network, and then the remainder describing what is being configured.

So by those old rules, CONFIG_MODULES would be wrong.  Since it affects the build system, it should be CONFIG_BUILD_MODULES.

What is configured?  BUILD_ system
What is controlled in the build system?  MODULE support.

**Review by cederom — CHANGES_REQUESTED** [review]
Lets finish the nomenclature change discussion resolution first.

**Comment by masayuki2009** [comment]
@xuxin930  @xiaoxiang781216 
I noticed that the PR does not work with kconfig-frontends but works with kconfiglib.
Do you mean that kconfig-frontends is no longer supported?

**Comment by xuxin930** [comment]
> @xuxin930 @xiaoxiang781216 I noticed that the PR does not work with kconfig-frontends but works with kconfiglib. Do you mean that kconfig-frontends is no longer supported?

hi @masayuki2009  i add both MODULE config and modules option in this patch https://github.com/apache/nuttx/pull/13532. 
which both work in two Kconfig implementation library.

**Pull request merged**
