### PR TITLE
nshlib: Don't select LIBC_NETDB automatically

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

since nshlib always call netdb API inside #ifdef CONFIG_LIBC_NETDB.
Depends on https://github.com/apache/nuttx/pull/10196.

## Impact

save the code size

## Testing

CI

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]

**Review by pkarashchenko — APPROVED** [review]

**Comment by pkarashchenko** [comment]
@xiaoxiang781216 is the dependency specified in the PR description correct?

**Comment by xiaoxiang781216** [comment]
> @xiaoxiang781216 is the dependency specified in the PR description correct?

It's wrong, update.

**Comment by SPRESENSE** [comment]
@xiaoxiang781216 
This change of Kconfig causes `defconfig` to be incompatible.
Please add the label `breaking change` and reflect it in the release notes.

**Comment by xiaoxiang781216** [comment]
Done.

**Pull request merged**
