### PR TITLE
examples/foc: add real time data capture with nxscope lib

### PR DESCRIPTION
**Pull request by raiden00pl**
## Summary

- examples/foc/foc_thr: fix mutex logic
- examples/foc/foc_thr: get controller type from controller ID
- examples/foc: add real time data capture with the NxScope library

## Impact
It's now possible to capture controller data easily and then visualizing them. Useful for controller tuning and debugging.

## Testing
Tested with nxscope client https://github.com/railab/nxscli
Data stream on UART works fine.
Data stream on full-speed CDCACM device adds too much uC overload which breaks FOC control loops and is not recommended (usbdev full-speed packet limit is too small). High-speed CDCACM should be more practical, but I don't have proper hardware to test.

### CODE REVIEW

**Review by cederom — APPROVED** [review]
looks cool! :-)

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by cederom** [comment]
> @raiden00pl: Tested with nxscope client https://github.com/railab/nxscli Data stream on UART works fine. Data stream on full-speed CDCACM device adds too much uC overload which breaks FOC control loops and is not recommended (usbdev full-speed packet limit is too small). High-speed CDCACM should be more practical, but I don't have proper hardware to test.

@raiden00pl did you consider USB HID? It uses small fast interrupt transfers and provides quite good portability (+python modules on the host side). There is an interesting discussion at https://github.com/libusb/hidapi/issues/274#issuecomment-1542958282 on improving transfers at low level and hidapi vs hidraw implementation for various OS in favor of hidraw replacing hidapi :-)

I have just ordered cheap ESP32-S2 devkits maybe they will provide necessary USB Device to play with.. and the second device has OLED Display :-)
1. https://allegro.pl/oferta/esp32-s2-mini-s2fn4r2-wifi-wemos-micropython-4mb-13135527193
2. https://allegro.pl/oferta/esp32-s2-pico-oled-wifi-wemos-micropython-4mb-13135527582

**Comment by raiden00pl** [comment]
@cederom that's interesting idea. I have no experience with usbdev as HID and NuttX doesn't seem to support HID device driver, so it's not so easy to verify :)

**Comment by cederom** [comment]
There is a HIDKBD example app but I did not use it yet.. lets see when ESP32-S2 comes and some free time to play :-)

https://github.com/apache/nuttx-apps/tree/master/examples/hidkbd

If that chip works with both USB and WiFi then I could finally create virtual hid tester / fuzzer one day.. I have this idea to emulate various USB HID devices for host stack and libraries testing.. as for now people need to have whole bunch of devices while usually it is only the descriptor part that matters and some payload data all this could be provided over WiFi :-)

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by mcuee** [comment]
@cederom 

For HIDAPI I have used the testing devices mentioned here.
https://github.com/libusb/hidapi/issues/478

ESP32 C3/S2/S3/C6 should have have USB HID support and BLE HID support.

**Pull request merged**
