### PR TITLE
Private requirement for wapi

### PR DESCRIPTION
**Pull request by Meissi-jian**
## Summary
1. add set/get  powersave api for lowpower device
2. add set/get  pmksa api for fast-wifi-connect requirement
3. add extend api for private needs,and can trans any struct but should equal with vendor
## Impact
N/A
## Testing
tested on vela product

### CODE REVIEW

**Comment by Meissi-jian** [comment]
should merge with https://github.com/apache/nuttx/pull/13074

**Review by anchao — CHANGES_REQUESTED** [review]
Please discard the wireless_priv.h commit, it does not serve any purpose to the community

**Comment by Meissi-jian** [comment]
> Please discard the wireless_priv.h commit, it does not serve any purpose to the community

Done

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
@Meissi-jian please fix ci error.

**Comment by Meissi-jian** [comment]
> @Meissi-jian please fix ci error.

@xiaoxiang781216   have been retrigger compile ci error fixed. Does this failure  the ci check about "Mixed case identifier found" need to be fixed?
  ```
  FAR cJSON *obj;
```

**Review by anchao — APPROVED** [review]

**Comment by anchao** [comment]
Let us ignore the script warning

**Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/wireless/wapi/src/util.c:82:6: error: Mixed case identifier found
Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/wireless/wapi/src/util.c:109:9: error: Mixed case identifier found
Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/wireless/wapi/src/util.c:1[25](https://github.com/apache/nuttx-apps/actions/runs/10811326134/job/29990486359?pr=2515#step:4:26):33: error: Mixed case identifier found
Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/wireless/wapi/src/util.c:131:6: error: Mixed case identifier found
Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/wireless/wapi/src/util.c:132:6: error: Mixed case identifier found**

**Pull request merged**
