### PR TITLE
build(bugfix): add missing --deppath

### PR DESCRIPTION
**Pull request by xuxin930**
## Summary

1. complete missing DEPPATH for applactions

## Impact

supplement missing code declaration

## Testing
CI

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by cederom — CHANGES_REQUESTED** [review]
* There are two different changes in this PR that should be provided as separate PR (one is about providing `DEPPATH` for `interpreters/wamr`, second changes global build behavior of `cp`  for `AROBJSRULES` in `Make.defs` it hides the copy operation).
* Please advise @patacongo @jerpelea @acassis  if the cp operation is okay to stay hidden I remember there was a discussion on mailing list about build process verbosity control.

**Comment by xuxin930** [comment]
> * There are two different changes in this PR that should be provided as separate PR (one is about providing `DEPPATH` for `interpreters/wamr`, second changes global build behavior of `cp`  for `AROBJSRULES` in `Make.defs` it hides the copy operation).

hi @cederom , thanks. I modified this PR into a single function, which is to supplement the missing code definition

**Review by cederom — APPROVED** [review]
Thank you @xuxin930 :-)

**Comment by xiaoxiang781216** [comment]
@xuxin930 please rebase your patch

**Pull request merged**
