### PR TITLE
{Bp-2655} examples: fix noteprint compile error 

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
fix noteprint compile error
The sched_note_string/bprintf/dump interfaces have been removed and replaced with printf and event

## Impact
RELEASE

## Testing
CI

Note
includes 
https://github.com/apache/nuttx-apps/pull/2596
https://github.com/apache/nuttx-apps/pull/2614
https://github.com/apache/nuttx-apps/pull/2650
https://github.com/apache/nuttx-apps/pull/2677
https://github.com/apache/nuttx-apps/pull/2681

### CODE REVIEW

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



This Pull Request appears to meet the basic NuttX requirements. 

**Here's a breakdown based on the provided information:**

**Strengths:**

* **Summary:**  Clearly states the purpose of the PR ("fix noteprint compile error") and provides a concise explanation of the change ("sched_note_string/bprintf/dump interfaces replaced with printf and event").
* **Impact:**  Indicates the PR is a bug fix affecting the RELEASE (likely meaning it's a critical fix).
* **Testing:** States that CI (Continuous Integration) was used for testing. This suggests automated tests were run.
* **Cross-referencing:** Links a related NuttX Apps Pull Request, which is good practice for related changes.

**Areas for Potential Improvement:**

* **Impact (Specificity):** While "RELEASE" suggests importance, a more detailed description of the impact would be helpful. For example:
    *  What functionality was broken before this fix?
    *  Which specific systems/configurations were affected by the compile error? 
* **Testing (Details):**  While mentioning "CI" is a good start, providing a summary of the specific tests run (even if just the names or categories) would strengthen the PR. 
* **Testing (Logs):**  The template requests "Testing logs before change" and "Testing logs after change."  While you might not want to paste full logs into the PR description, consider:
    *  Attaching log files to the PR.
    *  Providing snippets of the most relevant log entries.
    *  Linking to external log storage if available.

**Recommendation:**

While the PR seems to meet the basic requirements, adding more details in the "Impact" and "Testing" sections will provide reviewers with a better understanding of the changes and their validation.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by cederom — APPROVED** [review]
Thank you @jerpelea :-)

**Comment by jerpelea** [comment]
@lupyuen  

the CI does not use the right branch 
modified:   boards/arm/mps/mps3-an547/configs/ap/defconfig
modified:   boards/arm/mps/mps3-an547/configs/bl/defconfig

we do not have those configs in releases/12.7

@cederom please ignore the errors and merge the change

**Comment by lupyuen** [comment]
> the CI does not use the right branch

Thanks @jerpelea we're tracking the issue here:
https://github.com/apache/nuttx/issues/14513

**Pull request merged**
