### PR TITLE
.gitignore: Add .aider* to .gitignore

### PR DESCRIPTION
**Pull request by no1wudi**
## Summary
Add .aider* to .gitignore
## Impact
Minor
## Testing
CI

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
> Hey there @no1wudi what are `.aider*` files what are these used for and why want to ignore them? Some explanation in the PR and commit message would be nice :-)

here has the info: https://github.com/apache/nuttx/pull/13356

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by cederom** [comment]
Thanks @xiaoxiang781216 , this is in sync with https://github.com/apache/nuttx/pull/13356 in nuttx repo.

Still it would be nice to know what those files are, one sentence please next time in the git commit message @no1wudi :-)

**Review by cederom — APPROVED** [review]
Commit description with at least one sentence is required, please remember next time @no1wudi  :-)

**Comment by no1wudi** [comment]
@cederom Commit description added now

**Comment by cederom** [comment]
> @cederom Commit description added now

Thanks @no1wudi but it still does not answer any of the questions asked:

> Hey there @no1wudi what are .aider* files what are these used for and why want to ignore them? Some explanation in the PR and commit message would be nice :-)

I can see what this commit does from the diff so writing this again in the commit message makes no difference :-)

Message should be meaningful for someone else looking for the first time at the commit (or PR), not even the code, to quickly know why commit was introduced, **what it does**, **how**, and **why**. 

You can use one short sentence or a bullet list (`*` at line start). For instance:

.aider* are local temporary files used by code editor AI plugins, not part of the project code, should be git ignored.

Or: 

* .aider* files are temporary files created by local code editor AI plugins.
* those files are not part of the project code / repository.
* adding .aider* files to .gitignore separates temporary files from the repository code.

Such messages are very useful for others to quickly understand our work.. especially when there is a long list of commits / prs and we don't have time for in-depth analysis. Also kind of future reminder to self "what I did back then and why" :-)

**Comment by no1wudi** [comment]
@cederom Thanks, your suggestion is definitely a good idea.

**Pull request merged**
