### PR TITLE
New features and bug fix for Fastboot

### PR DESCRIPTION
**Pull request by JianyuWang0623**
## Summary
- New Feature
  - Auto download mode: [fastbootd:add delay ms for bootloader](https://github.com/apache/nuttx-apps/commit/a4556435a9ffbefb9708b54710412d69b6f515dd)   **-- by @anjiahao1** 
  - CMD: oem memdump & filedump : [system/fastboot: Support upload & oem(memdump, filedump) command](https://github.com/apache/nuttx-apps/commit/ac2665b2ab54eaa99caf20df3b71e48ccd23a711)
  - Retry if open EP failed: [system/fastboot: Retry if open EP failed](https://github.com/apache/nuttx-apps/commit/3fdd967aa133652d7d801165f9ef7c044a6064eb)
  - CMD: erase: [system/fastboot: erase - add driver independent](https://github.com/apache/nuttx-apps/commit/15a4fd99dd77d564a2648ed0c4a5ccbd0ec0b469), [system/fastboot: Complete the erase command](https://github.com/apache/nuttx-apps/commit/752829e050857a804c71af0d00f3722ba4ab3554)
- BugFix
  - [system/fastboot: fix crash when free invalid pointer](https://github.com/apache/nuttx-apps/commit/665962d4f955b91589d001666d9bc98c177d346a)  **-- by @Donny9**
  - [fastboot:enable O_CLOEXEC explicit](https://github.com/apache/nuttx-apps/commit/23361535fa95fe4a9c7f77bdbb15588c7bad7020)  **-- by wanggang26@xiaomi.com**
  -  [system/fastboot: Fix Out-of-bounds Write](https://github.com/apache/nuttx-apps/commit/cde41f48491e419a95c0997fda2f89692a4e44c1)
  - [system/fastboot: Fix that total_chunks of sparse_header maybe error](https://github.com/apache/nuttx-apps/commit/0db13892cf77108764d32671a9bd02c5db7a3f37)
  - [system/fastboot: Fix error that download_size always be zero](https://github.com/apache/nuttx-apps/commit/7873f36fbb8cf047b361fc3eb0acf87d1b348920)
  - [system/fastboot: Init total_imgsize to zero](https://github.com/apache/nuttx-apps/commit/97e817202679df50850c81c141590b4d136ba340)
  - [system/fastboot: Fix fd leak of fastboot_filedump_upload()](https://github.com/apache/nuttx-apps/commit/4da5b0f199f384a52f9a74718ce06de0d3040595)
  - [system/fastboot: Replace printf with syslog](https://github.com/apache/nuttx-apps/commit/4e478f9a30bfafdad7858d877a3544666b59f20b)
  - [Reduce the number of open() and close() to improve performance](https://github.com/apache/nuttx-apps/commit/5c220ffe4784edb150910d786ddfd7c4a15ba039)
  - [system/fastboot: fastboot flash - call fsync()](https://github.com/apache/nuttx-apps/commit/7772db0c6fc439fd863f37bcdbbd14c2e45d0ea3)
  - [system/fastboot: Support USB boardctl](https://github.com/apache/nuttx-apps/commit/f08fe95a381a6a8d3fe270c61f0e80aca515654a)
  - [fastboot tool: Status read failed while rebooting into bootloader](https://github.com/apache/nuttx-apps/commit/d2f7ac5b3f61366c608b887869da631642a8ab05)
- Depends
  - f08fe95a381a6a8d3fe270c61f0e80aca515654a depends on  https://github.com/apache/nuttx/pull/13367

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@JianyuWang0623 please fix the check error.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by cederom — APPROVED** [review]
Thank you @JianyuWang0623 looks like lots of useful work :-)

Please remember next time to add at least one simple sentence in each commit message what this change does why and how :-)

@xiaoxiang781216 follows the internals, go when all requests completed :-)

**Comment by cederom** [comment]
Still problem with just restarted check?

```
40d74f020 Merge cde41f48491e419a95c0997fda2f89692a4e44c1 into dfa3ce5f5dd4bebc1fd3f204889cb3fe392dc940
cde41f484 system/fastboot: Fix Out-of-bounds Write
0db13892c system/fastboot: Fix that `total_chunks` of sparse_header maybe error
7873f36fb system/fastboot: Fix error that download_size always be zero
97e817202 system/fastboot: Init total_imgsize to zero
4da5b0f19 system/fastboot: Fix fd leak of fastboot_filedump_upload()
ac2665b2a system/fastboot: Support upload & oem(memdump, filedump) command
3fdd967aa system/fastboot: Retry if open EP failed
23361535f fastboot:enable O_CLOEXEC explicit
4e478f9a3 system/fastboot: Replace printf with syslog
a4556435a fastbootd:add delay ms for bootloader
665962d4f system/fastboot: fix crash when free invalid pointer
5c220ffe4 Reduce the number of open() and close() to improve performance
7772db0c6 system/fastboot: fastboot flash - call fsync()
15a4fd99d system/fastboot: erase - add driver independent
f08fe95a3 system/fastboot: Support USB boardctl
752829e05 system/fastboot: Complete the erase command
d2f7ac5b3 fastboot tool: Status read failed while rebooting into bootloader
../nuttx/tools/checkpatch.sh -m -g dfa3ce5f5dd4bebc1fd3f204889cb3fe392dc940..HEAD
Remove Gerrit Change-ID's before submitting upstream
Error: Process completed with exit code 1.
```

**Comment by JianyuWang0623** [comment]
@xiaoxiang781216 @cederom 
- " Change-ID" removed.
- And will add more info to commit message next time.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by jerpelea — CHANGES_REQUESTED** [review]
please use English for commit messages !

**Review by acassis — APPROVED** [review]

**Comment by acassis** [comment]
@JianyuWang0623 please add an entry at nuttx/Documentation/ to let users know that fastboot is a supported application and include the usage examples that are commented in the source code

**Comment by JianyuWang0623** [comment]
@xiaoxiang781216 @acassis Add guide for fastboot: https://github.com/apache/nuttx/pull/13377 , [preview_link](https://github.com/JianyuWang0623/nuttx/blob/be83a84f57e35daadb55bbb33e703b3156149fdf/Documentation/applications/system/fastboot/index.rst)

**Pull request merged**
