### PR TITLE
wamr: add a few missing options to match the wamr repo counterpart

### PR DESCRIPTION
**Pull request by yamt**
## Summary
wamr: add a few missing options to match the wamr repo counterpart

### CODE REVIEW

**Comment by yamt** [comment]
i have no idea about the CI failure.
```
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
make: *** [tools/Unix.mk:689: olddefconfig] Error 1
  Disabling CONFIG_ARM_TOOLCHAIN_BUILDROOT
  Enabling CONFIG_ARM_TOOLCHAIN_CLANG
make: *** [tools/Unix.mk:689: olddefconfig] Error 1
  Building NuttX...
chip/stm32_gpio.c:41:11: note: '#pragma message: CONFIG_STM32_USE_LEGACY_PINMAP will be deprecated migrate board.h see tools/stm32_pinmap_tool.py'
   41 | #  pragma message "CONFIG_STM32_USE_LEGACY_PINMAP will be deprecated migrate board.h see tools/stm32_pinmap_tool.py"
      |           ^~~~~~~
  Normalize stm32f334-disco/nsh
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
make: *** [tools/Unix.mk:689: olddefconfig] Error 1
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
/usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
make: *** [tools/Unix.mk:712: savedefconfig] Error 1
make: *** [tools/Unix.mk:689: olddefconfig] Error 1
```

**Comment by acassis** [comment]
> i have no idea about the CI failure.
> 
> ```
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> make: *** [tools/Unix.mk:689: olddefconfig] Error 1
>   Disabling CONFIG_ARM_TOOLCHAIN_BUILDROOT
>   Enabling CONFIG_ARM_TOOLCHAIN_CLANG
> make: *** [tools/Unix.mk:689: olddefconfig] Error 1
>   Building NuttX...
> chip/stm32_gpio.c:41:11: note: '#pragma message: CONFIG_STM32_USE_LEGACY_PINMAP will be deprecated migrate board.h see tools/stm32_pinmap_tool.py'
>    41 | #  pragma message "CONFIG_STM32_USE_LEGACY_PINMAP will be deprecated migrate board.h see tools/stm32_pinmap_tool.py"
>       |           ^~~~~~~
>   Normalize stm32f334-disco/nsh
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> make: *** [tools/Unix.mk:689: olddefconfig] Error 1
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> /usr/bin/bash: line 1: arm-nuttx-eabi-gcc: command not found
> make: *** [tools/Unix.mk:712: savedefconfig] Error 1
> make: *** [tools/Unix.mk:689: olddefconfig] Error 1
> ```

Just rebase to fix the issue! @simbit18 modified the config script.

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by cederom — APPROVED** [review]
This change adds two new configuration parameters. CI build seems unrelated.

**Comment by simbit18** [comment]
Configuration/Tool: stm32f334-disco/nsh,CONFIG_ARM_TOOLCHAIN_CLANG
2024-07-18 11:48:27


https://github.com/apache/nuttx-apps/actions/runs/9990672271/job/27611925490?pr=2448#step:7:814
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	defconfig.tmp

**Review by simbit18 — APPROVED** [review]

**Comment by acassis** [comment]
> This change adds two new configuration parameters. CI build seems unrelated.

Please see simbit18 message for more details :-)

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
let's merge this minor change to avoid wasting ci resource.

**Pull request merged**
