### PR TITLE
Remove @ tag from all comments

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

and format the multiple line comments

## Impact

format change only

## Testing

ci

### CODE REVIEW

**Review by pkarashchenko — APPROVED** [review]

**Review by simbit18 — APPROVED** [review]

**Comment by yamt** [comment]
> Remove @ tag from all comments

why?

**Comment by xiaoxiang781216** [comment]
> > Remove @ tag from all comments
> 
> why?

Because all NuttX native comments don't use @, which are copied from other code base to identify the special element.

**Comment by yamt** [comment]
> > > Remove @ tag from all comments
> > 
> > 
> > why?
> 
> Because all NuttX native comments don't use @, which are copied from other code base to identify the special element.

well, what's the benefit we can gain by removing them?
i feel doxygen style comments are popular enough.

**Comment by xiaoxiang781216** [comment]
> > > > Remove @ tag from all comments
> > > 
> > > 
> > > why?
> > 
> > 
> > Because all NuttX native comments don't use @, which are copied from other code base to identify the special element.
> 
> well, what's the benefit we can gain by removing them?

Improve the consistency.

> i feel doxygen style comments are popular enough.

It isn't popular in NuttX code base.

**Review by yamt — APPROVED** [review]
i feel it makes sense for us to allow doxygen or some other structured comment style in future.

**Review by jerpelea — APPROVED** [review]

**Pull request merged**
