### PR TITLE
{Bp-2592} lvgl: upgrade to release/v9.2

### PR DESCRIPTION
**Pull request by jerpelea**
**Summary**
Upgrade LVGL to release v9.2.

Relates Issue: https://github.com/apache/nuttx-apps/issues/2461.

**Impact**
LVGL may have incompatible API changes in v9.2. You may need to manually fix them.
Please report to LVGL if any problems.

**Testing**
I compiled and tested with sim:lvgl_fb and stm32f429i-disco:lvgl. Both can compile without warning and launches successfully.

The lvgl/Kconfig is still copied from lvgl/lvgl/Kconfig. The file version mismatch check will be added in next release(v9.2.1)

### CODE REVIEW

**Comment by jerpelea** [comment]
please do not merge before https://github.com/apache/nuttx-apps/pull/2592

**Comment by jerpelea** [comment]
fixes https://github.com/apache/nuttx/issues/13825

**Review by cederom — CHANGES_REQUESTED** [review]
Thanks @jerpelea :-) As soon as LVGL 9.2.1 show up we will update URL to https://github.com/lvgl/lvgl/archive/refs/tags/v9.2.1.zip and will be ready to merge / backport just marking not to forget :-)

Wating for 9.2.1 nop nop nop :-)

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by cederom** [comment]
As promissed LVGL 9.2.1 is out! :-)
https://github.com/lvgl/lvgl/archive/refs/tags/v9.2.1.zip
https://github.com/lvgl/lvgl/archive/refs/tags/v9.2.1.tar.gz

**Comment by jerpelea** [comment]
backport updated

**Review by cederom — APPROVED** [review]
Thank you @jerpelea :-)

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
