### PR TITLE
Fix telnetd.c:57:5: error: 'CONFIG_SYSTEM_TELNETD_SESSION_STACKSIZE' undeclared

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

```
telnetd.c: In function 'telnetd_main':
Error: telnetd.c:57:5: error: 'CONFIG_SYSTEM_TELNETD_SESSION_STACKSIZE' undeclared (first use in this function); did you mean 'CONFIG_SYSTEM_TELNETD_SESSION_PRIORITY'?
   57 |     CONFIG_SYSTEM_TELNETD_SESSION_STACKSIZE,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     CONFIG_SYSTEM_TELNETD_SESSION_PRIORITY
```

## Impact

Kconfig

## Testing

ci

### CODE REVIEW

**Review by lupyuen — APPROVED** [review]

**Review by lupyuen — APPROVED** [review]

**Review by cederom — APPROVED** [review]
Thank you @xiaoxiang781216 :-)

**Comment by GUIDINGLI** [comment]
There are more than one places take CI error.
I think firstly resolve this obvious error.

And there are 3 PR fixes which are similar:
https://github.com/apache/nuttx-apps/pull/2713
https://github.com/apache/nuttx-apps/pull/2717
https://github.com/apache/nuttx-apps/pull/2716

I prefer this current one.
And I will merge this PR, and close others.

**Comment by lupyuen** [comment]
I think it's still failing, due to the defconfig? 
```text
Configuration/Tool: qemu-armv8a/netnsh_smp
Normalize qemu-armv8a/netnsh_smp
102d101
< CONFIG_SYSTEM_TELNETD_SESSION_STACKSIZE=8192
```
https://github.com/apache/nuttx-apps/actions/runs/11320114328/job/31477189995

**Comment by GUIDINGLI** [comment]
Here is the fix:
https://github.com/apache/nuttx/pull/14229

**Pull request merged**
