### PR TITLE
interpreter/toywasm: Update toywasm version

### PR DESCRIPTION
**Pull request by yamt**
## Summary
interpreter/toywasm: Update toywasm version

## Testing
Tested on esp32-devkitc.

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
let's squash the second patch into the first one.

**Comment by yamt** [comment]
> let's squash the second patch into the first one.

i'm not inclined to do so because the file in the first commit is a copy of machine-generated file and the second commit is a manual edit to appease nxstyle.

(while IMO there is no point to run nxstyle on these files, i don't have a better solution right now.)

**Comment by xiaoxiang781216** [comment]
If so, it's better to update the script to generate the code in the well format.

**Comment by yamt** [comment]
> If so, it's better to update the script to generate the code in the well format.

in future, maybe.
it's sad nxstyle doesn't have an auto formatting tool.

**Review by pkarashchenko — APPROVED** [review]

**Comment by xiaoxiang781216** [comment]
> > If so, it's better to update the script to generate the code in the well format.
> 
> in future, maybe. it's sad nxstyle doesn't have an auto formatting tool.

So, you have to sqaush the patch manually now.

**Comment by yamt** [comment]
> > > > If so, it's better to update the script to generate the code in the well format.
> > > 
> > > 
> > > in future, maybe. it's sad nxstyle doesn't have an auto formatting tool.
> > 
> > 
> > So, you have to sqaush the patch manually now.
> 
> i still prefer not to squash. but i will.

done

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
