### PR TITLE
examples/pipe: fix write usage

### PR DESCRIPTION
**Pull request by Cynerd**
## Summary
write returns in case some bytes were written but not everything can fit.

This wasn't the case in NuttX but commit
d0680fd1bc51b7ead0b068fb24a31a144d22dc6c introduced this standard behavior.

## Impact
This should fix CI as reported in https://github.com/apache/nuttx/pull/14667#issuecomment-2461197521.
## Testing
`pipe` was executed on custom same7 board and passed.

<details>

```
> pipe

pipe_main: Performing FIFO test
open_write_only: Opening FIFO for write access
open_write_only: Waiting for open_write_only thread
pipe_main: open_write_only returned 0
transfer_test: fdin=4 fdout=3
transfer_test: Starting transfer_reader thread
transfer_test: Starting transfer_writer thread
transfer_reader: started
transfer_test: Waiting for transfer_writer thread
transfer_writer: started
transfer_writer: 18200 bytes written
transfer_reader: 18200 bytes read
transfer_test: transfer_writer returned 0
transfer_test: Waiting for transfer_reader thread
transfer_test: transfer_reader returned 0
transfer_test: returning 0
transfer_test: fdin=4 fdout=3
transfer_test: Boost priority of transfer_readerthread to 101
transfer_test: Starting transfer_reader thread
transfer_reader: started
transfer_test: Starting transfer_writer thread
transfer_test: Waiting for transfer_writer thread
transfer_writer: started
transfer_reader: 18200 bytes read
transfer_writer: 18200 bytes written
transfer_test: transfer_writer returned 0
transfer_test: Waiting for transfer_reader thread
transfer_test: transfer_reader returned 0
transfer_test: returning 0
transfer_test: fdin=4 fdout=3
transfer_test: Starting transfer_reader thread
transfer_test: Boost priority of transfer_writerthread to 101
transfer_reader: started
transfer_test: Starting transfer_writer thread
transfer_writer: started
transfer_test: Waiting for transfer_writer thread
transfer_writer: 18200 bytes written
transfer_reader: 18200 bytes read
transfer_test: transfer_writer returned 0
transfer_test: Waiting for transfer_reader thread
transfer_test: transfer_reader returned 0
transfer_test: returning 0
transfer_test: fdin=4 fdout=3
transfer_test: Boost priority of transfer_readerthread to 101
transfer_test: Starting transfer_reader thread
transfer_reader: started
transfer_test: Boost priority of transfer_writerthread to 101
transfer_test: Starting transfer_writer thread
transfer_writer: started
transfer_test: Waiting for transfer_writer thread
transfer_writer: 18200 bytes written
transfer_reader: 18200 bytes read
transfer_test: transfer_writer returned 0
transfer_test: Waiting for transfer_reader thread
transfer_test: transfer_reader returned 0
transfer_test: returning 0

pipe_main: Performing pipe interlock test
interlock_test: Starting null_writer thread
interlock_test: Opening FIFO for read access
null_writer: started -- sleeping
null_writer: Opening FIFO for write access
null_writer: Opened /var/testfifo-2 for writing -- sleeping
interlock_test: Reading from /var/testfifo-2
null_writer: Closing /var/testfifo-2
interlock_test: read returned
interlock_test: Closing /var/testfifo-2
interlock_test: Waiting for null_writer thread
null_writer: Returning success
interlock_test: writer returned 0
interlock_test: Starting null_reader thread
interlock_test: Opening FIFO for write access
null_reader: started -- sleeping
null_reader: Opening FIFO for read access
null_reader: Opened /var/testfifo-2 for reading -- sleeping
interlock_test: Writing to /var/testfifo-2
interlock_test: write returned
interlock_test: Closing /var/testfifo-2
interlock_test: Waiting for null_reader thread
null_reader: Closing /var/testfifo-2
null_reader: Returning success
interlock_test: reader returned 0
interlock_test: Returning 0
pipe_main: FIFO interlock test PASSED
pipe_main: FIFO test PASSED

pipe_main: Performing pipe test
transfer_test: fdin=4 fdout=3
transfer_test: Starting transfer_reader thread
transfer_test: Starting transfer_writer thread
transfer_reader: started
transfer_test: Waiting for transfer_writer thread
transfer_writer: started
transfer_writer: 18200 bytes written
transfer_reader: 18200 bytes read
transfer_test: transfer_writer returned 0
transfer_test: Waiting for transfer_reader thread
transfer_test: transfer_reader returned 0
transfer_test: returning 0
transfer_test: fdin=4 fdout=3
transfer_test: Boost priority of transfer_readerthread to 101
transfer_test: Starting transfer_reader thread
transfer_reader: started
transfer_test: Starting transfer_writer thread
transfer_test: Waiting for transfer_writer thread
transfer_writer: started
transfer_reader: 18200 bytes read
transfer_writer: 18200 bytes written
transfer_test: transfer_writer returned 0
transfer_test: Waiting for transfer_reader thread
transfer_test: transfer_reader returned 0
transfer_test: returning 0
transfer_test: fdin=4 fdout=3
transfer_test: Starting transfer_reader thread
transfer_test: Boost priority of transfer_writerthread to 101
transfer_reader: started
transfer_test: Starting transfer_writer thread
transfer_writer: started
transfer_test: Waiting for transfer_writer thread
transfer_writer: 18200 bytes written
transfer_reader: 18200 bytes read
transfer_test: transfer_writer returned 0
transfer_test: Waiting for transfer_reader thread
transfer_test: transfer_reader returned 0
transfer_test: returning 0
transfer_test: fdin=4 fdout=3
transfer_test: Boost priority of transfer_readerthread to 101
transfer_test: Starting transfer_reader thread
transfer_reader: started
transfer_test: Boost priority of transfer_writerthread to 101
transfer_test: Starting transfer_writer thread
transfer_writer: started
transfer_test: Waiting for transfer_writer thread
transfer_writer: 18200 bytes written
transfer_reader: 18200 bytes read
transfer_test: transfer_writer returned 0
transfer_test: Waiting for transfer_reader thread
transfer_test: transfer_reader returned 0
transfer_test: returning 0

pipe_main: Performing redirection test
redirection_test: Starting redirect_writer task with fd=3
redirection_test: Starting redirect_reader task with fd=4
redirect_writer: started with fdout=3
redirection_test: Waiting for null_reader thread
redirect_reader: started with fdin=4

Four score and seven years ago our fathers broughtforth on this continent a new nation,
conceived in Liberty, and dedicated to the propositionthat all men are created equal.

Now we are engaged in a great civil war, testingwhether that nation, or any nation, so
conceived and so dedicated, can long endure. We are meton a great battle-field of that war.
We have come to dedicate a portion of that field, as afinal resting place for those who hredirect_writer: 1456 bytes written
ere
gave their lives that that nationredirect_writer: Returning success
 might live. It isaltogether fitting and proper that we
should do this.

But, in a larger sense, we can not dedicate - we cannot consecrate - we can not hallow - this ground.
The brave men, living and dead, who struggled here, haveconsecrated it, far above our poor power
to add or detract. The world will little note, nor longremember what we say here, but it can
never forget what they did here. It is for us theliving, rather, to be dedicated here to the
unfinished work which they who fought here have thus farso nobly advanced. It is rather for us to
be here dedicated to the great task remaining before us- that from these honored dead we take
increased devotion to that cause for which they gave thelast full measure of devotion - that we
here highly resolve that these dead shall not have diedin vain - that this nation, under God,
shall have a new birth of freedom - and that governmentof the people, by the people, for the
people, shall not perish from the earth.

redirect_reader: 1456 bytes read
redirect_reader: Returning success
redirection_test: Waiting...
redirection_test: returning 0
pipe_main: PIPE redirection test PASSED
pipe_main: PIPE test PASSED
```
</details>

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



No.  This PR description lacks crucial information.

Here's what's missing and why it's important:

* **Insufficient Summary:**  "write returns..." is too vague.  What *specifically* was changed in the code? Which function(s) were modified?  What was the previous, incorrect behavior?  The reference to the commit hash is helpful but insufficient; explain the change in human-readable terms.  A link to the relevant NuttX Issue is missing.
* **Incomplete Impact Assessment:**  While it mentions fixing a CI issue, it doesn't fully address all the impact points.  Consider:
    * **Impact on user:**  Does this change the behavior of applications using `write`?  Even if the change aligns with POSIX, it's still a change that might affect user code.
    * **Impact on hardware:**  Unclear.  While tested on a SAME7 board, does this change affect other architectures?  Explicitly state "NO" or provide details if "YES."  Similarly for drivers.
    * **Impact on documentation:** Does this change require documentation updates?
    * **Impact on compatibility:** Explicitly address backward compatibility.  Does this change break existing NuttX applications?
    * **Impact on security:**  Consider if this change has any security ramifications. Even if the answer is "NO," it should be explicitly stated.
* **Inadequate Testing:**  "pipe was executed..." is far too vague. What were the specific test cases? What were the *expected* outputs before and after the change? The provided log sections are empty.  Provide concrete examples of commands and their outputs, demonstrating both the previous broken behavior and the corrected behavior.  Include details about the build host used for testing.


**In short:** The PR description needs to be significantly more detailed to meet the NuttX requirements.  It must clearly articulate the change, its rationale, its impact across different aspects of the system, and provide verifiable testing evidence.

**Review by lupyuen — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by lupyuen** [comment]
Thanks @Cynerd: I cloned your branch and [enabled all the builds](https://github.com/nuttxpr/nuttx-apps/commit/fc85439e8b3b681583225cf6790994040cff91d6). I'll check the results here: https://github.com/nuttxpr/nuttx-apps/actions/runs/11724108240

**Comment by Cynerd** [comment]
> Thanks @Cynerd: I cloned your branch and [enabled all the builds](https://github.com/nuttxpr/nuttx-apps/commit/fc85439e8b3b681583225cf6790994040cff91d6). I'll check the results here: https://github.com/nuttxpr/nuttx-apps/actions/runs/11724108240

It still seems to fail for what ever reason. I will try those tests locally and see what is going on there.

**Comment by Cynerd** [comment]
@lupyuen is there a way to get logs from CI for arm-02 board sabre-6quad. That seems to be the only one that failed. Other runs seem to be running fast again. The only one that failed is sabre-6quad. I am trying to run tests for it locally and it passes. I see that tests create logs in my case, but there is no such file in the arm-02 artifact, and thus, I am unable to find out where it actually failed.

**Comment by lupyuen** [comment]
@Cynerd Sorry do you mean this log? I ran sabre-6quad:citest 3 hours ago:
https://github.com/NuttX/nuttx/actions/runs/11722647465/job/32652723982#step:7:115

**Comment by lupyuen** [comment]
rv-virt:citest also failed 12 hours ago, according to nuttx-dashboard.org 
https://gist.github.com/jerpelea/45f67d6dd6efba585b7a1e7a1f2c1216#file-ci-risc-v-05-log-L78

**Comment by Cynerd** [comment]
I mean this file: nuttx/boards/arm/imx6/sabre-6quad/configs/citest/logs/sabre-6quad/qemu/sabre-6quad_20241107_162834.log

It is log from pexpect.

**Comment by lupyuen** [comment]
Sorry what's the command to run citest? I have compiled sabre-6quad:citest in Docker, but I'm not sure how to run it:
```bash
tools/configure.sh sabre-6quad:citest
make
## What next?
```

**Comment by Cynerd** [comment]
```
python3 -m pytest -m qemu tools/ci/testrun/script -B sabre-6quad -P . -L boards/arm/imx6/sabre-6quad/configs/citest/logs/sabre-6quad/qemu -R qemu -k 'pipe'
```

**Comment by lupyuen** [comment]
Or something special about the way QEMU runs inside Docker?

**Comment by Cynerd** [comment]
> Or something special about the way QEMU runs inside Docker?

Possibly.. but why just for this one specific board? Or is it the only board that runs tests in Qemu? I am trying to run it in docker as well now. Will see..

**Comment by Cynerd** [comment]
Anyway I would be for merging this to fix at least CI runtime. The issue with sabre-6quad we could solve down the line.

**Comment by lupyuen** [comment]
BTW rv-virt:citest is also failing with QEMU inside Docker:
https://gist.github.com/jerpelea/45f67d6dd6efba585b7a1e7a1f2c1216#file-ci-risc-v-05-log-L78

**Comment by Cynerd** [comment]
@lupyuen can you please compare what you are doing with what I am doing? The full log of attempt in the docker: https://gist.github.com/Cynerd/81262ceaa32ac5719b453269e620cb0c

**Comment by lupyuen** [comment]
@Cynerd I ran the exact same steps and it works OK: https://gist.github.com/nuttxpr/bdb03952f774e711bafc4e7ae7d329c2

In the earlier log: `git clone https://github.com/apache/nuttx-apps apps`

That's the only difference I think.

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
