### PR TITLE
apps: Remove the check of CONFIG_SERIAL_TERMIOS

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
## Summary

If the code only change c_oflag, c_iflag and c_lflag, not c_cflag in termios.
Follow up the change from kernel: https://github.com/apache/nuttx/pull/8843

## Impact

Avoid the shell password echo to terminal

## Testing

sim:adb

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
Please ignore the remain nxstyle warning.

**Comment by patacongo** [comment]
Failing because of mixed case identifiers in modbus.

**Review by patacongo — APPROVED** [review]
Most of this change simply removes logic previously conditioned on CONFIG_SERIAL_TERMIOS but no longer needed because of NuttX PR #8843.  Most of this is straight forward, but easy to review thoroughly.

One consequence of this is that NuttX Issue #1667 should also be resolved.

**Comment by patacongo** [comment]
This can be merged since the only errors are due to mixed case identifiers and include files in the wrong location in modus.  Other reviewers should not hesitate to review this as I may very well have missed something.

**Pull request merged**
