### PR TITLE
github: add auto labeler for PR

### PR DESCRIPTION
**Pull request by raiden00pl**
## Summary
This PR adds auto labeler for nuttx-apps. 
Labels have been modified to better match nuttx-apps repo specification.

## Impact
Auto labeler for nuttx-apps

## Testing
CI

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



## NuttX PR Requirements Review:

**Meets Requirements?** Mostly

**Summary:** 
* The summary is acceptable, though it could be more detailed.  Specify *why* an auto-labeler is necessary and what specific label modifications were made. 

**Impact:**
*  **Insufficient detail:** This section requires specific answers (YES/NO) for each impact category, followed by a description if "YES." For example:
    *  **Impact on user:** YES. Users will need to familiarize themselves with the new label categories when interacting with issues and PRs.
    *  **Impact on documentation:**  YES. The contribution guidelines should be updated to reflect the new label usage for nuttx-apps.

**Testing:**
*  **Insufficient:** "CI" is not descriptive enough.  Provide specific build hosts and target details as requested. Include snippets of relevant log output demonstrating the labeler's correct functionality (e.g., an issue being opened and automatically receiving the appropriate labels).

**Recommendations for Improvement:**

1. **Expand the Summary:**  Explain the benefits of an auto-labeler for nuttx-apps (e.g., improved issue organization, easier contribution process). Provide a few examples of the modified labels and their purpose.
2. **Complete the Impact Section:** Provide YES/NO answers for each impact category and detailed explanations where applicable. 
3. **Provide Thorough Testing Information:**  List specific build hosts and target environments used for testing. Include relevant log snippets that demonstrate:
    * The auto-labeler functioning correctly.
    *  The expected labels being applied to new issues. 

By addressing these points, you will significantly improve the clarity and completeness of your PR, making it easier for reviewers to understand and approve your changes.

**Comment by cederom** [comment]
Thank you @raiden00pl :-) I think the labels needs to stay in sync with nuttx repo as there is some automation attached :-) Can you please add new labels without removing old ones on both nuttx and nuttx-apps repos? :-)

**Comment by raiden00pl** [comment]
Removed labels are for `Issues`. I don't think we have any automation related to that :)

**Review by cederom — APPROVED** [review]
Thank you @raiden00pl :-)

From what I remember labels were supposed to be the same for nuttx and nuttx-repos as Issue templates use them, maybe some automation, please confirm @acassis @jerpelea @lupyuen @xiaoxiang781216  :-)

**Review by lupyuen — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
