### PR TITLE
Issues: Added Issue templates

### PR DESCRIPTION
**Pull request by simbit18**
## Summary

**-Template**
 Bug report
Report a bug to improve NuttX stability

Feature request
Request an enhancement for NuttX

General Help
Get general support regarding NuttX

Of course, others can be added. !!! :)

**-Action**
An action for automatically labelling issues

 **Keywords**

Keywords are present in the dropdowns (the user can select more than one option) of the form Bug report and are:

    - BSD, Linux, Mac, Windows, Other
    - all, arm, arm64, avr, ceva, hc, mips, misoc, openrisc, renesas, risc-v, simulator, sparc, tricore, x86, x86_64, xtensa, z16, z80
    - Applications, Api, Board support, Build System, Configuring, Debugging, Drivers, File System, Installing, Kconfig, Kernel, Memory Management, Native port, Networking, OS Components, Posix, Sensors, Specific Peripheral

Of course these keywords are examples so you can add, edit or delete them.

**To work, the labels must have the same name as the keywords !!!**

**So before merging it is necessary that label keywords must first be entered manually!!!**

**My NuttX repository access permission levels do not allow me to add labels.**

[How to create a label manually](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#creating-a-label)

see [#12748](https://github.com/apache/nuttx/issues/12748)

## Impact
none
## Testing
CI

### CODE REVIEW

**Comment by cederom** [comment]
Could you please add BSD to the OS list @simbit18 ? :-) :-)

**Comment by simbit18** [comment]
Hi @cederom  sure !!!

**Comment by simbit18** [comment]
@cederom done !!!

**Review by jerpelea — APPROVED** [review]

**Comment by cederom** [comment]
Labels are created with some remarks:
* OS have `OS_` prefix (i.e. OS_BSD, OS_Linux, etc).
* arch has `arch_` prefix (i.e. arch_all, arch_arm, etc).
* areas are lowercase and slightly updated.
* label groups have the same color so they can be easily distinguished.

This is non-invasive change and can be easily updated by repo managers.

Please review labels and let me know if there is anything to update? Do we need labels descriptions too so they show up on the list somehow?

**Comment by simbit18** [comment]
@cederom  @acassis has already added the labels in the nuttx repository.

see the test issue  [12842](https://github.com/apache/nuttx/issues/12842)

**Comment by cederom** [comment]
ah okay will adjust right now :-)

**Comment by cederom** [comment]
updated :-) please verify :-

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
