### PR TITLE
{Bp-2639} system/uorb: bug fix and support flush/get_events api and comiple in aosp

### PR DESCRIPTION
**Pull request by jerpelea**
## Summary
    orb_flush: After you call orb_flush(), you can determine whether the flush is completed by listening to the POLLPRI event
    of fd and getting the event in orb_get_events.
    remove non-posix implement, include api and header file, let uorb compile in aosp.
    bug fix

## Impact
RELEASE

## Testing
CI

### CODE REVIEW

**Review by lupyuen — APPROVED** [review]

**Comment by lupyuen** [comment]
@jerpelea It's checking out from master, need to rebase I think
```text
Run actions/checkout@v4
  with:
    repository: apache/nuttx-apps
    path: sources/apps
    fetch-depth: 1
    token: ***
```

**Comment by jerpelea** [comment]
this is the apps git!

**Comment by lupyuen** [comment]
Ah my mistake, should be OK then :-)

**Comment by jerpelea** [comment]
please merge the apps PRs

**Pull request merged**
