### PR TITLE
stdio: Remove CONFIG_EOL_IS_XXX

### PR DESCRIPTION
**Pull request by no1wudi**
## Summary
Remove CONFIG_EOL_IS_XXX relative logic since serial driver will do the convertion.

Please ignore nxstyle error from `bas_fs.c`.
## Impact
Should be none.
## Testing
cle/vi/bas/readline

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
let's fix the style warning execpt "Mixer case"
https://github.com/apache/nuttx-apps/actions/runs/4249463510/jobs/7389640450

**Comment by no1wudi** [comment]
> let's fix the style warning execpt "Mixer case" https://github.com/apache/nuttx-apps/actions/runs/4249463510/jobs/7389640450

Fixed, and there also have `error: Multiple data definitions` from its origin code.

**Comment by xiaoxiang781216** [comment]
> > let's fix the style warning execpt "Mixer case" https://github.com/apache/nuttx-apps/actions/runs/4249463510/jobs/7389640450
> 
> Fixed, and there also have `error: Multiple data definitions` from its origin code.

This need be fixed too.

**Comment by no1wudi** [comment]
> This need be fixed too.

Done

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
