### PR TITLE
libc:getline support backspace

### PR DESCRIPTION
**Pull request by zhangwenjian111**
## Summary
getline function support backspace

## Impact
None

## Testing
sim qemu arm

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



**No, this PR does not meet the NuttX requirements.**

**Missing Information:**

* **Summary:**
    * Lacks a clear explanation of why the change is necessary. Is `getline`  broken? Is this a new feature request? 
    *  Missing details on how the backspace functionality is implemented.
* **Impact:** 
    * Even if the change seems minor, you need to carefully consider and document any potential impact. For example:
        * **Impact on user:** Will existing users who rely on the old `getline` behavior be affected?
        * **Impact on documentation:** Does this change require updates to the NuttX documentation?
* **Testing:**
    * **Insufficient Detail:**  "sim qemu arm" is not specific enough. Specify:
        * The exact simulator used (e.g., QEMU version)
        * The specific ARM architecture simulated
        * The NuttX configuration used
    * **No Logs:**  Provide actual testing logs (both before and after the change) to demonstrate the issue and the fix. 

**Recommendations:**

1. **Expand the Summary:**  Clearly state the problem or need this PR addresses and provide a concise technical overview of your implementation.
2. **Analyze Impact Thoroughly:** Carefully consider all potential impacts, even if they seem minor.  Document your reasoning for each "NO" answer. If the impact is "YES," provide a detailed explanation.
3. **Provide Specific Testing Information:** Include the following:
    * Simulator details: Version, architecture, etc.
    * NuttX configuration:  Board, build options
    *  **Complete Logs:** Copy and paste relevant sections of the build and runtime logs to demonstrate the issue before the change and the correct behavior after the change.

**Comment by cederom** [comment]
Isn't this already implemented and user selectable with Kconfig? See: https://nuttx.apache.org/docs/latest/applications/examples/termios/index.html.

Should getline also depend on those configuration parameters?

**Comment by xiaoxiang781216** [comment]
> Isn't this already implemented and user selectable with Kconfig? See: https://nuttx.apache.org/docs/latest/applications/examples/termios/index.html.
> 
> Should getline also depend on those configuration parameters?

Don't need. After https://github.com/apache/nuttx/pull/8843, the software terminal setting always exist, CONFIG_SERIAL_TERMIOS only control the hardware specific setting (e.g. baud rate).

**Review by cederom — APPROVED** [review]
Thank you @zhangwenjian111 :-)

**Pull request merged**
