### PR TITLE
nshlib: Add startup process buried points 

### PR DESCRIPTION
**Pull request by Gary-Hobson**
## Summary
1. nshlib: Add startup process buried points 
2. trace: fix trace dump crash 

## Testing
sim

### CODE REVIEW

**Comment by nuttxpr** [comment]
[**\[Experimental Bot, please feedback here\]**](https://github.com/search?q=repo%3Aapache%2Fnuttx+13552&type=issues)



**No, this PR does not fully meet the NuttX requirements.**

**Missing Information:**

* **Summary:**
    *  **Why** are these changes necessary?  Bug fixes? Enhancements? 
    * **How** do the changes work? Provide specifics about the buried points added and the cause of the trace dump crash and how it was fixed.
    * **Issue References:** Link any relevant NuttX or NuttX Apps issues.
* **Impact:** 
    * Address *all* impact categories (user, build, hardware, documentation, security, compatibility). Even if there's no impact, state "NO" explicitly for each.
* **Testing:**
    * **Insufficient Detail:** "sim" isn't descriptive enough. Specify the simulator (e.g., qemu-rv32) and the configuration used.
    * **Missing Logs:** Provide actual testing logs from *before* and *after* the changes.

**Recommendations:**

1. **Expand the Summary:** Explain the "why" and "how" for each change.
2. **Complete the Impact Assessment:**  Go through each category and provide a clear "YES" or "NO" along with a brief explanation if necessary.
3. **Provide Detailed Testing Information:** Specify the exact simulator, configurations, and include the relevant testing logs.

**Review by cederom — CHANGES_REQUESTED** [review]
Thank you @Gary-Hobson :-) There are build errors that need to be fixed :-)

**Review by xiaoxiang781216 — APPROVED** [review]

**Review by pkarashchenko — APPROVED** [review]

**Review by xiaoxiang781216 — APPROVED** [review]

**Comment by cederom** [comment]
My only remark is this is very useful feature, probably will be developed further in future, but as for quite a big change better description in the PR and some additional comments in the commit message would help understand the change better by others that want to use it too :-)
* Is existing API impacted anyhow? Will old code work the same way or needs an update?
* Is documentation update required  / necessary? Maybe it would be good to provide documentation on how to use new functionalities? Newcomers tend to start at documentation so share your inventions there too :-)
* If the buffer is too small, sure we can increase the buffer, but also overflow checks are necessary?

**Review by cederom — APPROVED** [review]
Thank you @Gary-Hobson :-)

**Pull request merged**
