### PR TITLE
examples: Refactoring bindings examples

### PR DESCRIPTION
**Pull request by kassane**
## Summary

Refactoring Zig and D examples

## Impact

This refactoring involves giving a better understanding of the usefulness of certain examples.
If these tools don't have any real appeal, then they're completely useless.

## Step changes

- [x] improvement `hello_zig`
- [x] use Zig `std.mem.Allocator` + std containers  in example (Zig std works in RTOS??)
- [x] improvement `hello_d` using `importC` (get nuttx include) on `betterC` mode no GC (garbage collector)
- [x] make another example, beyond hello_world.

## Testing

- Zig make easy C ffi

#### How?
https://github.com/apache/nuttx-apps/blob/19e8f6ab1402dd097b8b2c7e6c4f0e426314e5fa/examples/hello_zig/hello_zig.zig#L29-L35
https://github.com/apache/nuttx-apps/blob/19e8f6ab1402dd097b8b2c7e6c4f0e426314e5fa/examples/hello_zig/hello_zig.zig#L39-L40
https://github.com/apache/nuttx-apps/blob/19e8f6ab1402dd097b8b2c7e6c4f0e426314e5fa/examples/hello_zig/hello_zig.zig#L52-L59

```bash
$ qemu-system-riscv32 \
    -semihosting \
    -M virt,aclint=on \
    -cpu rv32 -smp 8 \
    -bios none \
    -kernel nuttx -nographic
NuttShell (NSH) NuttX-12.6.0-RC1
nsh> hello_zig
[rv-virt]: Hello, Zig!
```
---

Dlang

```bash
$ qemu-system-riscv32 \
    -semihosting \
    -M virt,aclint=on \
    -cpu rv32 -smp 8 \
    -bios none \
    -kernel nuttx -nographic
NuttShell (NSH) NuttX-12.6.0-RC1
nsh> hello_d
Hello World, [generic-rv32]!
hello_d_main: Saying hello from the dynamically constructed instance
HelloWorld: mSecret=0
DHelloWorld.HelloWorld: CONSTRUCTION FAILED!
Constructor
hello_d_main: Saying hello from the instance constructed on the stack
HelloWorld: mSecret=42
DHelloWorld.HelloWorld: Hello, World!!
Destructor
```

## Reference
- https://github.com/apache/nuttx/pull/13139
- https://github.com/apache/nuttx/issues/12960

cc: @lupyuen

### CODE REVIEW

**Comment by kassane** [comment]
About Zig's progress.

Of all these languages that have internal or external facilities for interoperability with C (some C++ too) zig proves to be very practical, providing built-in auto-conversion (C2Zig).

However, in the future Zig will make LLVM optional and some of the features will no longer be provided by default (maybe as an add-on).
In this case `@cImport` will no longer be provided and will follow the same Rust style (like, bindgen-rs) as the third-party `translate-c` application.

**Note:** unlike bindgen-rs and importC (I don't know how to evaluate Swift yet), `@cImport` and `translate-c` not only "translate" the declarations in the header but also the implementation (header-only) if available. Similar to c2rust!!

### FFI method

- Rust: need bindgen or c2rust
- D: importC
- Swift: Bridging header or LLVM modulemap.
- Zig: `@cImport/@cInclude` or translate-c

- https://github.com/ziglang/zig/issues/20630
- https://github.com/ziglang/zig/issues/20875

**Comment by xiaoxiang781216** [comment]
@kassane please fix ci warning:
```
Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/examples/hello_d/nuttx_std.c:2:1: error: Relative file path does not match actual file
Error: /home/runner/work/nuttx-apps/nuttx-apps/apps/examples/hello_d/nuttx_std.c:32:1: error: "Private/Public Functions" not found! File will not be checked
Error: Process completed with exit code 1.
```

**Comment by kassane** [comment]
### WiP

```bash
USAGE: gpio_zig [-t <pintype>] [-w <signo>] [-o <value>] <driver-path>
                gpio_zig -h
Where:
        <driver-path>: The full path to the GPIO pin driver.
        -t <pintype>:  Change the pin to this pintype (0-10):
        -w <signo>:    Wait for a signal if this is an interrupt pin.
        -o <value>:    Write this value (0 or 1) if this is an output pin.
        -h: Print this usage information and exit.
Pintypes:
         0: GPIO_INPUT_PIN
         1: GPIO_INPUT_PIN_PULLUP
         2: GPIO_INPUT_PIN_PULLDOWN
         3: GPIO_OUTPUT_PIN
         4: GPIO_OUTPUT_PIN_OPENDRAIN
         5: GPIO_INTERRUPT_PIN
         6: GPIO_INTERRUPT_HIGH_PIN
         7: GPIO_INTERRUPT_LOW_PIN
         8: GPIO_INTERRUPT_RISING_PIN
         9: GPIO_INTERRUPT_FALLING_PIN
        10: GPIO_INTERRUPT_BOTH_PIN
```

**Comment by lupyuen** [comment]
@kassane sorry I missed this, wonder if it might be better to blink the LED like [leds_rust](https://lupyuen.github.io/articles/rust6#blink-the-led), instead of doing GPIO?

That's because we can test it on QEMU RISC-V, which has an [LED Driver](https://github.com/apache/nuttx/pull/12762). We don't have a GPIO Driver for QEMU. Thanks!

**Comment by kassane** [comment]
> @kassane sorry I missed this, wonder if it might be better to blink the LED like [leds_rust](https://lupyuen.github.io/articles/rust6#blink-the-led), instead of doing GPIO?

For me it's no problem. I can change the solution to `leds_zig`.

I will do it then!

**Comment by kassane** [comment]
@lupyuen , curiosity example using Swift embedded.

> [!NOTE]
> Curious note regarding leds_swift.
>
>Having completed the zig example. I have taken the time and concepts to try to implement the swift port (newly embedded).
>However, embedded ABI support is incomplete, for example Variadic functions are not yet available on the embedded module.
> C Macro support also limited, need rewrite port

Swift-Embedded support status:
https://github.com/swiftlang/swift/blob/main/docs/EmbeddedSwift/EmbeddedSwiftStatus.md#embedded-standard-library-breakdown

leds-sample: https://gist.github.com/kassane/03a792f92b2430b350429dfa51dd5532

```swift
let _ULEDBASE: UInt = 0 // You need to set this to the correct value
let _IOC_TYPE_MASK: UInt = 0xff << 8 // Adjust this based on your system's IOC structure

func _IOC(_ type: UInt, _ nr: UInt) -> UInt {
    return (type << 8) | nr
}

func _IOC_TYPE(_ nr: UInt) -> UInt {
    return (nr & _IOC_TYPE_MASK) >> 8
}

func _ULEDIOCVALID(_ c: UInt) -> Bool {
    return _IOC_TYPE(c) == _ULEDBASE
}

func _ULEDIOC<T: BinaryInteger>(_ nr: T) -> T {
    return T(_IOC(_ULEDBASE, UInt(nr)))
}

let ULEDIOC_SUPPORTED: Int32 = _ULEDIOC(0x0001)
let ULEDIOC_SETALL : Int32 =   _ULEDIOC(0x0003)
```

```bash
# fd = open(CONFIG_EXAMPLES_LEDS_DEVPATH, O_WRONLY)
error: 'open' is unavailable: Variadic function is unavailable
# var ret = ioctl(fd, ULEDIOC_SUPPORTED, supported)
note: 'ioctl' has been explicitly marked unavailable
```

**Review by lupyuen — APPROVED** [review]
Looks great thanks!

**Review by xiaoxiang781216 — APPROVED** [review]

**Pull request merged**
